#!/bin/bash
# This program is intended for Linux use only. If you want to run this on separate platforms like Windows, refer to the developer docs.
separator="------------------------------------------------------------------"
clear
echo "Starting..."
sleep 1
clear
echo "Creating your new Windows virtualised sandbox..."
echo Current user account: $USER;
mkdir /home/$USER/sandbox/
echo $separator;
echo "Creating new virtual machine creator...";
echo "Run /sandbox/new";
echo $separator
cp ./latest/new /home/$USER/sandbox;
echo "Opening a new virtual machine window... Only gnome-terminal will work with this tool.";
chmod +x /home/$USER/sandbox/new
gnome-terminal --command /home/$USER/sandbox/new
